osx_image: xcode9.2
language: objective-c
script:
- sudo gem install cocoapods -v 1.4.0
- travis_retry pod repo update > /dev/null
- pod lib lint --use-libraries --allow-warnings || pod lib lint --allow-warnings
